flexflow/flexflow-train

README.md
=> install FlexFlow (not TASO)

include/model.h, python/Makefile, python/example/alexnet.py, python/example/mlp.py, python/flexflow/core/flexflow_cbinding.py, python/flexflow_c.cc, python/flexflow_c.h, src/ops/conv_2d.cu, src/ops/element_binary.cu, src/ops/element_unary.cu, src/ops/embedding.cu, src/ops/flat.cu, src/ops/linear.cu, src/ops/pool_2d.cu, src/runtime/model.cc
1. add batch_norm to python
2. fix the Functional API by setting the numInputs correctly. It was set to 0 before.
=> Fix the C++ Functional API

python/Makefile, python/example/keras/ary.py, python/example/keras/callback.py, python/example/keras/mnist_func.py, python/example/keras/mnist_seq_nested.py, python/example/keras/reuters_mlp.py, python/flexflow/core/flexflow_cbinding.py, python/flexflow/keras/__init__.py, python/flexflow/keras/backend/__init__.py, python/flexflow/keras/backend/flexflow_backend.py, python/flexflow/keras/callbacks.py, python/flexflow/keras/layers/__init__.py, python/flexflow/keras/layers/base_layer.py, python/flexflow/keras/layers/convolutional.py, python/flexflow/keras/layers/core.py, python/flexflow/keras/layers/input_layer.py, python/flexflow/keras/layers/merge.py, python/flexflow/keras/layers/pool.py, python/flexflow/keras/models/__init__.py, python/flexflow/keras/models/base_model.py, python/flexflow/keras/models/input_layer.py, python/flexflow/keras/models/model.py, python/flexflow/keras/models/sequential.py, python/flexflow/keras/models/tensor.py, python/flexflow/keras/optimizers.py, python/flexflow_c.cc, python/flexflow_c.h, python/test.sh
1. clean up the keras API, add assert if not supported. 
2. similar as real keras, now Input is a wrapper of InputLayer class instead of Tensor class, so the model summary can print the InputLayer now.  
3. add callback for LearningRateScheduler
4. add flexflow as keras "backend"
=> clean up keras API

CMakeLists.txt
Update the CMake build for the new example directories.
=> Fix CMake build paths for new example dirs

examples/cpp/DLRM/dlrm.cc, src/ops/embedding.cu, src/runtime/model.cc, src/runtime/simulator.cc
[DLRM] bug fixes in the DLRM app
=> [Simulator] fix a bug in generating random config

python/flexflow/onnx/model.py, src/ops/conv_2d.cu
Fixes some small bugs in the grouped convolution implementation.
=> Bugfixes in grouped convolution implementation

include/config.h, include/simulator.h, src/runtime/model.cc, src/runtime/simulator.cc
Add flag that allows exporting the `SimTask` graph as a dot file.
=> Add ability to export final task graph

.circleci/config.yml
Added config file for circleCI which runs nvidia-smi.
=> Added circleci config with nvidia-smi.

.circleci/config.yml, examples/python/native/accuracy.py, examples/python/native/alexnet.py, examples/python/native/cifar10_cnn.py, examples/python/native/mnist_cnn.py, examples/python/native/mnist_mlp.py, test_python_native.sh, tests/accuracy_tests.sh
Included tests for mnist_mlp and mnist_cnn. Will include more tests after getting feedback from the team.
=> Adding tests for python native examples

INSTALL.md
typos + expanding on some things after having difficulties and getting answers from the maintainers of the project.
=> [install doc] various tweaks

python/flexflow/torch/fx.py, python/flexflow/torch/model.py
Added new handlers for elementwise multiplication interpreting from a torch.fx `.ff` file.
=> [FX] Added new operator handler for elementwise multiplication.

INSTALL.md
- fix example path
- make steps numbered so it's clear there a sequence of steps
- adjust examples to be more readable - add definition of the expected buffer size
=> [install] doc improvements

python/bindings.cc
With this change pybind11 performance matches cffi.
=> [pybind11] add support for begin_trace and end_trace

examples/python/pytorch/resnet152_DDP_training.py
Corrected timing method in order to account for the fact that GPUs execute processes asynchronously. This is done as mentioned in this [article](https://deci.ai/the-correct-way-to-measure-inference-time-of-deep-neural-networks/).
Also added new flag --batchsize for specifying the batchsize for the training run.
=> [ModelTiming] Corrected timing method

python/flexflow/core/flexflow_type.py, python/flexflow/torch/fx.py, python/flexflow/torch/model.py
Added new operator support to FX for "getattr" needed toexport ViT.
=> [FX] Added getattr operator to PyTorchModel class

python/flexflow/torch/model.py
Support for the actual operator to be loaded from the .ff file and executed on FF.
=> [FX] Added support for batch_matmul operators to be able to be read from file.

include/ffconst.h, include/model.h, python/bindings.cc, python/flexflow/core/flexflow_cbinding.py, python/flexflow/torch/model.py, python/flexflow_c.cc, python/flexflow_c.h, src/metrics_functions/metrics_functions.cc, src/ops/element_unary.cu
Identity operator added to the source code along with its respective pybind.
=> [Op] Added support for Identity operator

python/flexflow/core/flexflow_cbinding.py
Added needed class Identity(Op) in order to load the identity operator into FlexFlow.
=> [FX] Added class for cbinding Op for Identity operator.

CMakeLists.txt, INSTALL.md, config/config.inc, config/config.linux, python/CMakeLists.txt, python/Makefile, python/flexflow/core/__init__.py
Now that March release is done, make pybind11 the default.
=> [Python] make pybind11 default python bindings

examples/cpp/ResNet/resnet.cu, examples/cpp/ResNet/resnet.h, examples/cpp/resnext50/resnext.cc, examples/cpp/split_test_2/split_test_2.cc, gdb/pretty_print.py, include/flexflow/graph.h, include/flexflow/substitution.h, src/runtime/cpp_driver.cc, src/runtime/graph.cc, src/runtime/substitution.cc, src/runtime/tensor.cc
- Fix up some header import paths
- Begin work on getting optimal views from the new graph search algorithm
- Fix `check_matches_graph` assertion (i.e. `g_nodes != r_nodes`)
=> Fix headers, check_matches_graph, graph search views

include/flexflow/ops/embedding.h, src/ops/embedding.cc, src/runtime/graph.cc, src/runtime/substitution.cc
Also add missing `params_hash` support in `Embedding`
=> Make Graph::graph_optimize handle multi-input graphs

examples/cpp/split_test_2/split_test_2.cc, include/flexflow/graph.h, include/flexflow/memory_optimization.h, include/flexflow/simulator.h, include/flexflow/substitution.h, src/runtime/graph.cc, src/runtime/simulator.cc, src/runtime/substitution.cc
This is to add the initial version of memory search algorithm.
- This pull request was made to be easy to review (no unnecessary refactor or optimization or formatting, just simple functionality)
- This was made without polluting the normal Unity search algorithm. This causes a bunch of code duplication but I think it's better to not change unity's verified flow for now. And since we will need to refactor the code in the future, we can tolerate some code duplication for now.
- The whole search procedure can and probably should be refactored for better code organization and performance. But we should do that after we agree on the design.
- I added many doxygen documentation to explain the use of functions. Hopefully newcomers could understand the procedure more easily with those comments. …
=> Initial version of search procedure with memory consideration

CMakeLists.txt, include/flexflow/ffconst_utils.h, include/flexflow/model.h, include/flexflow/substitution.h, include/flexflow/substitution_loader.h, src/runtime/ffconst_utils.cc, src/runtime/layer.cc, src/runtime/model.cc, src/runtime/operator.cc, src/runtime/simulator.cc, src/runtime/substitution.cc, src/runtime/substitution_loader.cc, src/tools/substitutions_to_dot/CMakeLists.txt, src/tools/substitutions_to_dot/substitution_to_dot.cpp, tests/unit/test_substitution_loader.cc
Fixes the issue reported by @eric-zheng.
=> Add params_hash for ElementBinary, unify get_operator_type_name

.gitmodules, FlexFlow.mk, src/runtime/substitution_loader.cc
Fix the makefile. Now the makefile could automatically detect the files under src folder, so it should be much easier to maintain.
=> fix makefile

src/runtime/graph.cc
CI is broken on master, this change fixes formatting so it passes.
=> Fix master formatting

src/runtime/substitution.cc
=> Fused parallel breakdown in dot graph

include/flexflow/substitution_loader.h, src/runtime/ffconst_utils.cc
A couple small fixes for bugs reported by Teresa
=> Fix Teresa bugs

python/flexflow/torch/model.py
=> [PyTorch] Fix type check in ScalarFloorDivNode

include/flexflow/ops/aggregate.h, include/flexflow/ops/aggregate_spec.h, src/ops/aggregate.cc, src/ops/aggregate_spec.cc
Implemented inference function to take in batch tensors as inputs for aggregate and aggregate_spec
=> feat: implement inference batch tensors for aggregate

.github/workflows/helpers/gpu_ci_helper.py
Fix some bugs that were introduced with PR #528 and could not detected during the PR testing phase because the new workflow could not run until the PR was merged into master
Linked Issues:
- Issue #
- Closes #
=> [CI] - Bug fix

cmake/legion.cmake, docker/flexflow-environment/Dockerfile
Linked Issues:
- Issue #
- Closes #
=> [Python] - Update python version

.github/workflows/gpu-ci-daemon.yml
Linked Issues:
- Issue #
- Closes #
=> [CI] - Daemon fix

examples/cpp/inference/mixture_of_experts/moe.cc, examples/cpp/inference/mixture_of_experts/moe.h, include/flexflow/model.h, include/flexflow/ops/aggregate.h, include/flexflow/ops/experts.h, include/flexflow/ops/experts_params.h, src/ops/aggregate.cc, src/ops/experts.cc, src/ops/experts.cpp, src/ops/experts.cu, src/runtime/graph.cc, src/runtime/model.cc, src/runtime/substitution.cc
Linked Issues:
- Issue #
- Closes #
=> Implement Experts operator

examples/cpp/inference/mixture_of_experts/moe.cc, examples/cpp/inference/mixture_of_experts/moe.h, include/flexflow/ops/experts.h, src/ops/experts.cc, src/ops/linear.cc
This PR changes the MoE experts operator to introduce support for tensors that have more than 2 dimensions.
Linked Issues:
- Issue #
- Closes #
=> [MoE][Experts] - Add support for tensors with more than 2 dimensions

README.md
Linked Issues:
- Issue #599 
- Closes #599 
=> replace keras example with a link. fix #599

include/flexflow/ops/experts.h, include/flexflow/ops/experts_params.h, src/ops/experts.cc, src/ops/experts.cpp, src/ops/experts.cu, src/runtime/graph.cc, src/runtime/model.cc, src/runtime/substitution.cc
A lighter weight version of PR #612  , allowing us to replace the implementation of the expert operator, without the kernel, which is still under development.
Linked Issues:
- Issue #
- Closes #
=> [Inference][Experts] - New experts operator (except for the kernel)

include/flexflow/ffconst.h, include/flexflow/model.h, include/flexflow/operator_params.h, include/flexflow/ops/inc_multihead_self_attention.h, include/flexflow/ops/inc_multihead_self_attention_params.h, src/ops/inc_multihead_self_attention.cc, src/ops/inc_multihead_self_attention.cu, src/runtime/model.cc
Implementing incremental multi-head self-attention.
Linked Issues:
- Issue #
- Closes #
=> [IncMultiHeadSelfAttention] initial implementation

.github/workflows/gpu-ci.yml, .github/workflows/helpers/gpu_ci_helper.py
Linked Issues:
- Issue #
- Closes #
=> [CI] - Fix new OpenSSL issue

.github/workflows/gpu-ci-daemon.yml, .github/workflows/multinode-test.yml
Linked Issues:
- Issue #
- Closes #
=> [CI] - Fix remaining open-ssl related issues

src/ops/experts.cc, src/ops/experts.cu
This PR fixed minor issues within the inference experts kernel. It also added numerical tests in experts.cc for debugging purposes, which should be replaced with unit tests.
Linked Issues:
- Issue #
- Closes #
=> [MoE][Experts] Fixed bug and verified experts kernel

examples/cpp/inference/inference_config.h, examples/cpp/inference/transformers/transformers.cc, include/flexflow/batch_config.h, src/ops/experts.cu
Linked Issues:
- Issue #
- Closes #
=> [Inference] Experts kernel bug fix

examples/cpp/inference/inference_config.h, src/ops/experts.cu, src/runtime/cuda_helper.cu
Linked Issues:
- Issue #
- Closes #
=> [Inference][Experts] - Add comprehensive testing to fused Experts operator, and fix bugs

.github/workflows/gpu-ci.yml, conda/flexflow-cpu.yml, examples/python/keras/gather.py, python/flexflow/keras/backend/internal.py, python/flexflow/keras/models/base_model.py, tests/multi_gpu_tests.sh
Linked Issues:
- Issue #
- Closes #
=> [Keras] Surface up gather in Keras

examples/cpp/inference/data_generator.cc, examples/cpp/inference/data_generator.h, examples/cpp/inference/dataloader.cc, examples/cpp/inference/inference_config.h, examples/cpp/inference/mixture_of_experts/moe.cc, examples/cpp/inference/mixture_of_experts/moe.h
Linked Issues:
- Issue #
- Closes #
=> Load data from files.

src/ops/experts.cc, src/ops/experts.cu, src/ops/inc_multihead_self_attention.cc, src/ops/inc_multihead_self_attention.cu
Linked Issues:
- Issue #
- Closes #
=> [Inference] - Update tests and Fix bugs discovered by Inference tests

src/ops/rms_norm.cc
Linked Issues:
- Issue #
- Closes #
=> fix machine view

src/runtime/request_manager.cpp, tests/cpp_gpu_tests.sh
Linked Issues:
- Issue #
- Closes #
=> [Inference] - Fix small issues

.github/workflows/gpu-ci.yml, tests/cpp_gpu_tests.sh, tests/multi_gpu_tests.sh
Linked Issues:
- Issue #
- Closes #
=> [GPU tests] - Fix CI error by reducing GPU memory

include/flexflow/ops/element_unary.h, include/flexflow/ops/element_unary_params.h, include/flexflow/ops/reduce.h, include/flexflow/ops/reduce_params.h, include/flexflow/ops/reshape.h, include/flexflow/ops/reshape_params.h, src/ops/element_unary.cc, src/ops/reduce.cc, src/ops/reshape.cc
Linked Issues:
- Issue #
- Closes #
=> Add layer_guid for elementwise unary, reshape and reduce

.github/workflows/gpu-ci.yml, examples/python/keras/regularizer.py, include/flexflow/ffconst.h, include/flexflow/model.h, include/flexflow/ops/kernels/linear_kernels.h, include/flexflow/ops/linear.h, include/flexflow/ops/linear_params.h, python/flexflow/core/flexflow_cffi.py, python/flexflow/keras/layers/core.py, python/flexflow/keras/models/base_model.py, python/flexflow/keras/regularizers.py, python/flexflow/type.py, python/flexflow_c.cc, python/flexflow_c.h, src/ops/kernels/linear_kernels.cu, src/ops/linear.cc, tests/cpp_gpu_tests.sh, tests/multi_gpu_tests.sh
Adds support for L2 kernel regularizer for linear layers. 
Linked Issues:
- Issue #
- Closes #
=> L2 Kernel regularizer for linear

examples/cpp/inference/.gitignore, examples/cpp/inference/LLAMA/dataloader.cc, examples/cpp/inference/LLAMA/llama.cc, examples/cpp/inference/LLAMA/llama.h, examples/cpp/inference/file_loader.cc, examples/cpp/inference/file_loader.h, examples/cpp/inference/models/llama.cc, src/ops/inc_multihead_self_attention.cu, src/ops/spec_inc_multihead_self_attention.cu, src/ops/tree_inc_multihead_self_attention.cu
Linked Issues:
- Issue #
- Closes #
=> [Inference][LLAMA] - Fix code to load W_out weight

examples/cpp/inference/gpt_tokenizer.cpp, include/flexflow/ops/beam_topk.h, include/flexflow/ops/inc_multihead_self_attention.h, include/flexflow/ops/spec_inc_multihead_self_attention.h, include/flexflow/ops/tree_inc_multihead_self_attention.h, src/ops/beam_topk.cu, src/ops/inc_multihead_self_attention.cu, src/ops/spec_inc_multihead_self_attention.cu, src/ops/tree_inc_multihead_self_attention.cu
Linked Issues:
- Issue #
- Closes #
=> Kernel bug fix

inference/file_loader.cc
Linked Issues:
- Issue #
- Closes #
=> file path adapt

.github/workflows/gpu-ci-skip.yml, include/flexflow/batch_config.h, include/flexflow/inference.h, inference/.gitignore, inference/incr_decoding/incr_decoding.cc, inference/spec_infer/spec_infer.cc, src/ops/tree_inc_multihead_self_attention.cu, src/runtime/batch_config.cc, src/runtime/beam_search_batch_config.cc, src/runtime/inference_manager.cc, src/runtime/request_manager.cc, src/runtime/tree_verify_batch_config.cc, tests/inference_tests.sh
Linked Issues:
- Issue #
- Closes #
=> [Inference] - Alignment tests

.github/workflows/gpu-ci-skip.yml, .github/workflows/gpu-ci.yml, inference/incr_decoding/incr_decoding.cc, inference/models/llama.cc, inference/spec_infer/spec_infer.cc, inference/utils/download_llama_weights.py, inference/utils/download_opt_weights.py, src/ops/kernels/rms_norm_kernels.cu, src/ops/kernels/softmax.cu, src/ops/tree_inc_multihead_self_attention.cu, src/runtime/request_manager.cc, tests/inference/huggingface_inference.py, tests/inference_tests.sh
Linked Issues:
- Issue #
- Closes #
=> [Inference] - Add half precision & HuggingFace alignment tests + Speed tests

.github/workflows/multinode-test.yml
Linked Issues:
- Issue #
- Closes #
=> Fix multinode test

.github/workflows/gpu-ci-skip.yml, .github/workflows/gpu-ci.yml, tests/inference/huggingface_inference.py, tests/inference_tests.sh
Linked Issues:
- Issue #
- Closes #
=> Fix inference test

.github/workflows/multinode-test.yml, CMakeLists.txt
Linked Issues:
- Issue #
- Closes #
=> Fix UCX multinode test

.github/workflows/gpu-ci.yml, CMakeLists.txt
Linked Issues:
- Issue #
- Closes #
=> [Inference] - Fix build issues

README.md
Linked Issues:
- Issue #
- Closes #634 
=> Remove incomplete sentence in readme

src/ops/inc_multihead_self_attention.cc, src/ops/inc_multiquery_self_attention.cc, src/ops/linear.cc, src/ops/spec_inc_multihead_self_attention.cc, src/ops/tree_inc_multihead_self_attention.cc, src/runtime/parallel_tensor.cc
Linked Issues:
- Issue #
- Closes #
=> [Inference] - Fix linear region requirement

examples/cpp/inference/mixture_of_experts/moe.h, include/flexflow/inference.h, inference/spec_infer/spec_infer.cc, src/runtime/request_manager.cc
Linked Issues:
- Issue #
- Closes #
=> Revert "[Inference] fix bug when init_length + beam_depth > max_num_tokens"

examples/python/pytorch/mt5/mt5_ff.py, include/flexflow/model.h, include/flexflow/ops/kernels/softmax_kernels.h, include/flexflow/ops/layer_norm.h, include/flexflow/ops/softmax.h, include/flexflow/ops/softmax_params.h, include/flexflow/parallel_ops/replicate.h, include/flexflow/utils/cuda_helper.h, python/flexflow/core/flexflow_cffi.py, python/flexflow/torch/model.py, python/flexflow_c.cc, python/flexflow_c.h, src/loss_functions/loss_functions.cc, src/loss_functions/loss_functions.cu, src/metrics_functions/metrics_functions.cc, src/metrics_functions/metrics_functions.cu, src/ops/element_unary.cu, src/ops/kernels/softmax.cu, src/ops/layer_norm.cc, src/ops/layer_norm.cu, src/ops/softmax.cc, src/runtime/cuda_helper.cu, src/runtime/graph.cc, src/runtime/substitution.cc
align with huggingface version Bert model forward and backward.
Linked Issues:
- Issue #
- Closes #
=> fix bert training issue.

include/flexflow/batch_config.h, inference/spec_infer/spec_infer.cc, src/runtime/request_manager.cc
Linked Issues:
- Issue #
- Closes #
=> [SpecInfer] Fix bug when init_length + beam_depth > MAX_SEQ_LENGTH and performance issue.

.github/workflows/gpu-ci.yml, tests/inference_tests.sh
Linked Issues:
- Issue #
- Closes #
=> [Inference] - Save output of inference test as an artifact 

src/runtime/simulator.cpp, src/runtime/simulator.cu
Linked Issues:
- Issue #
- Closes #
=> fixup: always disable hijack

include/flexflow/ops/beam_topk.h, src/ops/arg_topk.cc, src/ops/beam_topk.cc, src/ops/beam_topk.cpp, src/ops/beam_topk.cu
Linked Issues:
- Issue #
- Closes #
=> change batch_size to num_active_tokens

inference/models/configs/opt_13B.json
add opt 13B config to evaluate the OPT-13B on a single GPU by using offload
=> add opt 13B config

.github/workflows/docker-build.yml
Linked Issues:
- Issue #
- Closes #
=> Docker fix

docker/run.sh
Linked Issues:
- Issue #
- Closes #
=> [Docker] - Make it easier to attach inference weights to docker

config/config.linux
Linked Issues:
- Issue #
- Closes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/flexflow/FlexFlow/895)
=> Allow passing parameters to `config.linux`

inference/models/configs/opt_30B.json, src/ops/spec_inc_multihead_self_attention.cu
Linked Issues:
- Issue #
- Closes #
=> fix Spec_Inc bias

conda/flexflow.yml, requirements.txt
Linked Issues:
- Issue #
- Closes #
=> Fix conda in CI

python/flexflow/serve/serve.py
Adding missing f for f-string
Linked Issues: N/A
Issues closed by this PR: N/A
=> [Bug fix] Adding missing f for f-string

include/flexflow/flexflow_c.h, python/flexflow/core/flexflow_cffi.py, python/flexflow/serve/__init__.py, python/flexflow/serve/serve.py, src/c/flexflow_c.cc, src/runtime/request_manager.cu
This PR adds GenerationResult as the return value of llm.generate
Linked Issues:
- Issue #
- Closes #994 
=> add GenerationResult to the Python interface

lib/utils/include/utils/graph/adjacency_digraph.h, lib/utils/include/utils/graph/adjacency_multidigraph.h, lib/utils/include/utils/graph/digraph.h, lib/utils/include/utils/graph/node.h
Fix to following error:
Linked Issues:
- Issue #
- Closes #
=> Fix AdjacencyMultiDiGraph default construction error

python/flexflow/serve/serve.py
Linked Issues:
- Issue #
- Closes #993
=> Support loading local model

lib/utils/include/utils/type_traits_core.h
Added missing iterator include to type_traits_core
Linked Issues:
- Issue #
- Closes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/flexflow/FlexFlow/1015)
=> Added missing iterator include

.github/workflows/docker-build.yml, .github/workflows/helpers/install_cudnn.sh, docker/build.sh, docker/publish.sh, docker/pull.sh, docker/run.sh
Linked Issues:
- Issue #
- Closes #1029
=> Build docker images in more cuda versions

.github/workflows/gpu-ci.yml, docker/build.sh, docker/pull.sh, docker/run.sh, include/flexflow/flexflow_c.h, include/flexflow/request_manager.h, inference/incr_decoding/incr_decoding.cc, inference/spec_infer/spec_infer.cc, python/flexflow/core/flexflow_cffi.py, python/flexflow/serve/serve.py, src/c/flexflow_c.cc, src/runtime/request_manager.cc
Linked Issues:
- Issue #
- Closes #
=> Automatic bos/eos token determination, plus docker fix

lib/runtime/src/ops/conv_2d.cc
- Fix typo in `conv2d.cc`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/flexflow/FlexFlow/1135)
=> Conv2D Typo

.github/workflows/docker-build.yml, .github/workflows/helpers/oracle_con.py
This PR built upon the oracle_runner PR and updated the environment value with the corresponding oracle instance FlexFlow_CI test id. At the same time, there is also some code cleanup added. 
Linked Issues:
- Issue #
- Closes #
=> Oracle instance turn on fix 

.github/workflows/gpu-ci-daemon.yml, .github/workflows/gpu-ci.yml, .github/workflows/multinode-test.yml, python/flexflow/serve/__init__.py, python/flexflow/serve/models/falcon.py, python/flexflow/serve/serve.py
Changes needed to support Huggingface's Falcon model after today's changes: https://huggingface.co/tiiuae/falcon-7b/commit/898df1396f35e447d5fe44e0a3ccaaaa69f30d36
Linked Issues:
- Issue #
- Closes #
=> Support new Falcon model

CMakeLists.txt, cmake/pip_install/CMakeLists.txt, python/flexflow/core/flexflowlib.py
Linked Issues:
- Issue #
- Closes #1095
=> Fix `pip` issues affecting some platforms

setup.py
Linked Issues:
- Issue #
- Closes #
=> [Python] - Automatically install Rust with `pip install` if not available

inference/incr_decoding/incr_decoding.cc, inference/models/falcon.h, inference/spec_infer/spec_infer.cc, python/flexflow/core/__init__.py, python/flexflow/serve/models/__init__.py, python/flexflow/serve/models/base.py, python/flexflow/serve/models/falcon.py, python/flexflow/serve/models/llama.py, python/flexflow/serve/models/mpt.py, python/flexflow/serve/models/opt.py, python/flexflow/serve/models/starcoder.py, python/flexflow/serve/serve.py
Linked Issues:
- Issue #
- Closes #1154
=> Fix model configs (Falcon in C++, LLAMA in Python)

src/ops/element_unary.cpp, src/ops/element_unary.cu, src/ops/layer_norm.cpp, src/ops/layer_norm.cu
Linked Issues:
- Issue #
- Closes #
=> fix gelu, layer norm backward

include/flexflow/ops/inc_multihead_self_attention.h, include/flexflow/ops/kernels/inc_multihead_self_attention_kernels.h, inference/file_loader.cc, inference/models/falcon.cc, python/flexflow/serve/models/falcon.py, python/flexflow/serve/models/starcoder.py, src/ops/inc_multihead_self_attention.cc, src/ops/inc_multihead_self_attention.cpp, src/ops/inc_multihead_self_attention.cu, src/ops/spec_inc_multihead_self_attention.cc, src/ops/spec_inc_multihead_self_attention.cpp, src/ops/spec_inc_multihead_self_attention.cu, src/ops/tree_inc_multihead_self_attention.cc, src/ops/tree_inc_multihead_self_attention.cpp, src/ops/tree_inc_multihead_self_attention.cu, tests/inference/cpp_inference_tests.sh, tests/inference/python_inference_tests.sh, tests/inference/python_test_configs/generate_configs.py
Linked Issues:
- Issue #1133 
- Closes #1133 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/flexflow/FlexFlow/1190)
=> Optimize attention kernel v2 1.0, use Gemm replace GemmStridedBatch

include/flexflow/batch_config.h, include/flexflow/request_manager.h, src/ops/inc_multihead_self_attention.cpp, src/ops/inc_multihead_self_attention.cu, src/ops/spec_inc_multihead_self_attention.cpp, src/ops/spec_inc_multihead_self_attention.cu, src/runtime/batch_config.cc, src/runtime/beam_search_batch_config.cc, src/runtime/request_manager.cc, src/runtime/tree_verify_batch_config.cc
Linked Issues:
- Issue #
- Closes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/flexflow/FlexFlow/1194)
=> Rename `token_start_offset` to `first_token_depth_in_request`

.github/workflows/prebuild-legion.yml
Linked Issues:
- Issue #
- Closes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/flexflow/FlexFlow/1207)
=> Fix Legion prebuild workflow

config/config.linux
Linked Issues:
- Issue #
- Closes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/flexflow/FlexFlow/1210)
=> Fix Legion prebuild workflow (3)

MULTI-NODE.md
This PR adds documentation for multi node installation using UCX on top of https://github.com/flexflow/FlexFlow/pull/938
Linked Issues:
- Issue #
- Closes #938
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/flexflow/FlexFlow/1221)
=> Add documentation for multi node installation using UCX

src/ops/inc_multihead_self_attention.cu
Linked Issues:
- Issue #
- Closes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/flexflow/FlexFlow/1238)
=> Fix attention 

inference/incr_decoding/incr_decoding.cc, src/ops/add_bias_residual_layer_norm.cc, src/ops/fused.cc, src/ops/inc_multihead_self_attention.cc, src/ops/layer_norm.cc, src/ops/linear.cc, src/ops/lora_linear.cc, src/ops/residual_layer_norm.cc, src/ops/residual_rms_norm.cc, src/ops/rms_norm.cc, src/ops/sigmoid_silu_multi.cc, src/ops/softmax.cc, src/parallel_ops/allreduce.cc, src/runtime/inference_manager.cc
Linked Issues:
- Issue #
- Closes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/flexflow/FlexFlow/1241)
=> use grad to store peft in/output

src/ops/inc_multihead_self_attention.cu
Linked Issues:
- Issue #
- Closes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/flexflow/FlexFlow/1247)
=> Fix link issue

include/flexflow/model.h, python/flexflow/serve/models/opt.py, src/ops/kernels/linear_kernels.cu, src/runtime/model.cc
Linked Issues:
- Issue #
- Closes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/flexflow/FlexFlow/1271)
=> Fuse bias + relu in OPT

.github/workflows/gpu-ci.yml, CMakeLists.txt, cmake/pip_install/CMakeLists.txt, include/flexflow/mapper.h, include/flexflow/model.h, include/flexflow/operator.h, include/flexflow/request_manager.h, src/mapper/mapper.cc, src/ops/linear.cc, src/runtime/inference_manager.cc, src/runtime/model.cc
Linked Issues:
- Issue #
- Closes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/flexflow/FlexFlow/1286)
=> Revert "Bug fixes and update Legion version"

SERVE.md, docs/source/chatbot.rst, docs/source/prompt_template.rst, docs/source/rag.rst, docs/source/serve_fastapi.rst
- Added documentation in README for Python Usecases.
- Modified invalid links in flexflow serve documentation.
Linked Issues:
- Issue #
- Closes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/flexflow/FlexFlow/1291)
=> Docs Modification for Python Usecases

docker/build.sh, docker/pull.sh, docker/run.sh
Linked Issues:
- Issue #
- Closes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/flexflow/FlexFlow/1308)
=> support cuda 12.1 and cuda 12.2

.github/workflows/docker-build-skip.yml, .github/workflows/docker-build.yml, README.md, docker/README.md, docker/pull.sh, src/runtime/model.cc
Linked Issues:
- Issue #
- Closes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/flexflow/FlexFlow/1318)
=> Fix NCCL tear down issue, update docker pre-build cuda version list

.proj.toml, flake.lock, flake.nix
This renames previous `.lockshaw.toml` to `.proj.toml` and commits it into the repo itself in hopes of easing development and eventually allowing CI to be moved to also use `proj`
Linked Issues:
- Issue #
- Closes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/flexflow/FlexFlow/1350)
=> Commit proj toml and update proj version

.github/README.md, SERVE.md
Fix docs.
- Closes #1371
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/flexflow/FlexFlow/1372)
=> doc: fix c++ serving example

include/flexflow/batch_config.h, include/flexflow/ops/kernels/lora_linear_kernels.h, inference/python/ff_peft.py, src/ops/kernels/lora_linear_kernels.cu, src/ops/lora_linear.cc, src/runtime/batch_config.cc, src/runtime/request_manager.cc
Linked Issues:
- Issue #
- Closes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/flexflow/FlexFlow/1446)
=> Save weights after end of finetuning

include/flexflow/flexflow_c.h, include/flexflow/ops/lora_linear_params.h, inference/peft/peft.cc, inference/utils/upload_peft_model.py, python/flexflow/core/flexflow_cffi.py, src/c/flexflow_c.cc, src/ops/lora_linear_params.cc
Linked Issues:
- Issue #
- Closes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/flexflow/FlexFlow/1450)
=> PEFT model upload

.github/workflows/per-lib-check.yml
Add compiler to CI
Linked Issues:
- Issue #
- Closes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/flexflow/FlexFlow/1457)
=> Add compiler to CI

include/flexflow/ops/kernels/inc_multihead_self_attention_kernels.h, src/ops/attention.cu
This PR fixes a potential compilation issue with certain gcc/CUDA versions.
Linked Issues:
- Issue #
- Closes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/flexflow/FlexFlow/1456)
=> Minor compilation bug fix

include/flexflow/model.h, src/runtime/model.cc, src/runtime/request_manager.cc
Linked Issues:
- Issue #
- Closes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/flexflow/FlexFlow/1481)
=> Fix nccl-induced segfault

.github/runs-on.yml
Add repo config for testing https://runs-on.com/ (has to be on the main branch, hence the early PR for testing). 
Linked Issues:
- Issue #
- Closes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/flexflow/flexflow-train/1559)
=> Add runs-on repo config

.github/runs-on.yml
Linked Issues:
- Issue #
- Closes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/flexflow/flexflow-train/1589)
=> Add AWS linux AMI to runs-on configuration for testing

.github/runs-on.yml
Linked Issues:
- Issue #
- Closes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/flexflow/flexflow-train/1590)
=> Pin runs-on images

flake.lock
Linked Issues:
- Issue #
- Closes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/flexflow/flexflow-train/1600)
=> Update proj to fix issue with proj benchmark'ing a single benchmark

.github/runs-on.yml
Linked Issues:
- Issue #
- Closes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/flexflow/flexflow-train/1602)
=> Update runs-on image

.github/runs-on.yml, .github/workflows/tests.yml
Linked Issues:
- Issue #
- Closes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/flexflow/flexflow-train/1607)
=> Add custom AMI for GPU CI

.github/runs-on.yml
Linked Issues:
- Issue #
- Closes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/flexflow/flexflow-train/1609)
=> Add gpu-enabled ubuntu AMI

.github/runs-on.yml
Linked Issues:
- Issue #
- Closes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/flexflow/flexflow-train/1610)
=> Key AMI by name so repeated PRs are unnecessary

CONTRIBUTING.md, README.md
Linked Issues:
- Issue #
- Closes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/flexflow/flexflow-train/1612)
=> Add section on EditorConfig to setup guide in CONTRIBUTING.md
