flexflow/flexflow-train

INSTALL.md
README.md
examples/AlexNet/Makefile
examples/DLRM/Makefile.devgpu
examples/InceptionV3/Makefile
examples/candle_uno/Makefile
ffcompile.sh

add submodule commands to README
define CUDNN_HOME location of CUDNN
update LD_LIBRARY_PATH after building examples
remove hardcoded directory paths to protobuf in includes and libs all Makefiles
always use the local protoc because if you use the systeem protoc it might have a version conflict with your protobuf sources
Note that examples camera_uno and DLRM do not build.  AlexNet and InceptionV3 build ok.

updates to readme and install process after testing from new repo clone

---

src/runtime/model.cc

Otherwise with `FF_ENABLE_NCCL=0` and `USE_GASNET=0`, you get the following error message:
```
/home/users/unger/FlexFlow/src/runtime/model.cc: In function 'int main(int, char**)':
/home/users/unger/FlexFlow/src/runtime/model.cc:2602:24: error: 'MPI_Init' was not declared in this scope
MPI_Init(&argc, &argv);
```

Add an ifdef around MPI_Init

---

CMakeLists.txt
python/CMakeLists.txt
python/main.cc

Removed unnecessary import of flexflow.core. This is required because
Realm::Python::PythonModule::import_python_module is not an
exported symbol of the Realm shared library.
nm legion/lib/librealm.so | grep import_python_module | c++filt
0000000000fefb10 t Realm::Python::PythonModule::import_python_module(char const*)
flexflow.core is explictly imported by user python code.
Testing:
mkdir build
cd build
cmake .. -G Ninja -DCUDA_ARCH="60,70" -DCUDNN_ROOT="${CUDNN_ROOT_DIR}"
ninja flexflow_python
cd ..
./python/flexflow_python examples/python/onnx/mnist_mlp.py -ll:py 1 -ll:gpu 2 -ll:fsize 3072 -ll:zsize 12192 -t 1

[cmake] fix cmake build of flexflow_python

---

python/flexflow/onnx/model.py

New operator handler added to the ONNXModel class. This allows one to import certain models directly such as [RegNet](https://github.com/facebookresearch/ClassyVision/blob/master/classy_vision/models/regnet.py) and ResNet from torchhub.

[ONNX] Added new operator handler handleGlobalAveragePool to the ONNNXModel class

---

examples/python/pytorch/export_regnet_fx.py
examples/python/pytorch/regnet.py

Added new files for testing RegNet training with FlexFlow.
The first file `export_regnet_fx.py` creates the file `regnetX32gf.ff` which in turn is loaded by `regnet.py` to run the training.

[FX] Added RegNet example for training with the FX class.

---

examples/python/keras/candle_uno/candle_uno.py
examples/python/native/alexnet.py
examples/python/native/bert_proxy_native.py
examples/python/native/cifar10_cnn.py
examples/python/native/cifar10_cnn_attach.py
examples/python/native/cifar10_cnn_concat.py
examples/python/native/dlrm.py
examples/python/native/inception.py
examples/python/native/mnist_cnn.py
examples/python/native/mnist_mlp.py
examples/python/native/mnist_mlp_attach.py
examples/python/native/multi_head_attention.py
examples/python/native/print_input.py
examples/python/native/print_layers.py
examples/python/native/resnet.py
examples/python/native/split.py
examples/python/native/tensor_attach.py
examples/python/onnx/alexnet.py
examples/python/onnx/cifar10_cnn.py
examples/python/onnx/mnist_mlp.py
examples/python/onnx/resnet.py
examples/python/pytorch/cifar10_cnn.py
examples/python/pytorch/mnist_mlp.py
examples/python/pytorch/mnist_mlp_torch2.py
examples/python/pytorch/regnet.py
examples/python/pytorch/resnet.py
examples/python/pytorch/torch_vision.py

The FFConfig constructor now parses args.

[FFConfig] calling ffconfig.parse_args() is no longer required

---

examples/python/native/alexnet.py
examples/python/native/cifar10_cnn_concat.py
examples/python/native/inception.py
examples/python/native/multi_head_attention.py
examples/python/native/resnet.py
examples/python/native/split.py
examples/python/onnx/alexnet.py
examples/python/onnx/cifar10_cnn.py
examples/python/onnx/mnist_mlp.py
examples/python/onnx/resnet.py
examples/python/pytorch/regnet.py
examples/python/pytorch/resnet.py
examples/python/pytorch/torch_vision.py

This will ease the burden of migrating to pybind11.

[python] simplify dataloader code in examples

---

examples/python/keras/candle_uno/candle_uno.py
examples/python/native/alexnet.py
examples/python/native/bert_proxy_native.py
examples/python/native/inception.py
examples/python/native/multi_head_attention.py
examples/python/native/resnet.py
examples/python/onnx/alexnet.py
examples/python/onnx/resnet.py
examples/python/pytorch/regnet.py
examples/python/pytorch/resnet.py
examples/python/pytorch/torch_vision.py

Many python files were not import numpy and were instead
picking up numpy from the flexflow.core * import. This will
not work with pybind11 flexflow.core.

[python] add explicit numpy import

---

.gitmodules
CMakeLists.txt
include/config.h
include/model.h
include/random_utils.h
src/runtime/model.cc
src/runtime/simulator.cu
tests/unit/CMakeLists.txt
tests/unit/test_random_utils.cc

Add propagation mutation support into FlexFlow's search. Can be enabled with the `--enable-propagation` flag.
Also adds the gtest test framework into FlexFlow for use when testing unit testing functions that don't require the whole legion stack to be running.

Implement MCMC propagation support

---

python/bindings.cc
python/flexflow/keras/models/base_model.py
python/flexflow/keras_exp/models/model.py

With this change, Keras models now work with pybind11.
Testing:
FF_USE_PYBIND=1 ./python/flexflow_python examples/python/keras/func_cifar10_alexnet.py -ll:py 1 -ll:gpu 2 -ll:fsize 3072 -ll:zsize 12192 --epochs 1

[Python] extend pybind11 to support keras models

---

flexflow
python/CMakeLists.txt
python/bindings.cc
python/flexflow/core/__init__.py
python/main.cc

FlexFlow now works with the native python. FlexFlow could now
be run from Jupyter notebooks.
Testing:
FF_USE_PYBIND=1 PYTHONPATH=$(pwd) python ./examples/python/native/alexnet.py  -ll:gpu 2 -ll:fsize 3072 -ll:zsize 12192 --epochs 1

[Python] add support for being able to run with native python

---

python/bindings.cc

Fixes: #139
Testing:
% FF_USE_PYBIND=1 PYTHONPATH=$(pwd) python ./examples/python/native/alexnet.py -ll:py 1 -ll:gpu 2 -ll:fsize 3072 -ll:zsize 12192 --epochs 1
Using pybind11 flexflow bindings.
Traceback (most recent call last):
File "./examples/python/native/alexnet.py", line 1, in <module>
from flexflow.core import *
File "/private/home/msb/code/FlexFlow/flexflow/core/__init__.py", line 28, in <module>
begin_flexflow_task(sys.argv)
ValueError: -ll:py is not supported when using native python

[Python] throw an exception when -ll:py is passed to native python

---

CMakeLists.txt
examples/cpp/MLP_Unify/CMakeLists.txt
gdb/pretty_print.py
include/config.h
include/dominators.h
include/dot_file.h
include/graph.h
include/hash_utils.h
include/model.h
include/simulator.h
src/parallel_ops/combine.cc
src/runtime/graph.cc
src/runtime/model.cc
src/runtime/simulator.cc
src/runtime/substitution.cc
tests/unit/test_dominators.cc
tests/unit/test_dot.cc

I haven't determined if this actually speeds up the dp algorithm, and the implementation itself is not perfectly efficient (a bunch of unnecessary copies in the implementations of `GraphStructure`), but it at least makes the implementation a lot cleaner and provides an asymptotic speedup to the existing way of finding the bottleneck.
Also added: 
- `gdb/pretty_print.py` is a gdb pretty-printing module that can be built on to make gdb's printing of FlexFlow types much more readable
- the `--compgraph` can be used to output the final unify graph as a dot file

Add dominator-based bottleneck detection

---

python/flexflow/core/flexflow_type.py
python/flexflow/torch/fx.py
python/flexflow/torch/model.py

-  Deleted the intermediate_values dictionary added previously as its use was redundant with the existing tensor_dict object.
-  Separated the functionality of floor_divide into floor_divide and scalar_floordivide and made that last one so that it can handle operations between scalars.
- Finally changed the parsing of the reshape operator so that it can handle different forms in which reshape is used in torch.fx, effectively supporting polymorphism.

[FX] Refactored floor_divide and reshape operators so they reuse existing structure.

---

CMakeLists.txt

Fixes the following error:
CMake Error at CMakeLists.txt:103:
Parse error.  Expected "(", got newline with text "
".

[CMake] fix cmake build

---

include/model.h
python/bindings.cc
python/flexflow/core/flexflow_cbinding.py
python/flexflow/torch/fx.py
python/flexflow/torch/model.py
python/flexflow_c.cc
python/flexflow_c.h
src/ops/element_unary.cu

- Deleted FLOOR_DIV operator for tensors as it is not supported on pytorch, there is no easy way to compute it's backwards step gradient.

[Op] Deleted FLOOR_DIV for tensors

---

python/flexflow/torch/fx.py

- Previously the EXPAND parser for fx didn't consider all types of parameters it could have, now it is able to accept a variable number of parameters and to have them be obtained from other tensor's atributtes.

[FX] Corrected behaviour of the EXPAND parser in fx

---

python/flexflow/torch/model.py

- Added placeholder for LAYER_NORM on FX that only executes a IDENTITY operator in its place, this will in turn be changed when the operator is added to FF
- Added placeholder for EXPAND operator placeholder in the same way as for LAYER_NORM.
- Corrected how the transpose operator parameters are used, just a problem with indexing.

[FX] Added placeholder ops and corrected TRANSPOSE operator

---

python/flexflow/core/flexflow_type.py
python/flexflow/torch/fx.py

This takes in account the creation of custom parameters on pytroch, this is not done on the forward pass and so it's not detected by FX. This is why the named_parameters attribute must inspected in order to detect custom parameters.

[FX] Added parser for initialization of custom parameters.

---

CMakeLists.txt
include/flexflow/dominators.h
include/flexflow/graph.h
include/flexflow/graph_structures.h
src/runtime/graph.cc
tests/unit/test_disjoint_set.cc
tests/unit/test_dominators.cc
tests/unit/test_dot.cc
tests/unit/test_machine_view.cc
tests/unit/test_parallel_config.cc
tests/unit/test_random_utils.cc

Fix a bug in `Graph::split_horizontal` where the resulting subgraphs could have multiple parents. 
Example: 
```
digraph taskgraph {
node1 [label="1"];
node2 [label="2"];
node3 [label="3"];
node4 [label="4"];
node5 [label="5"];
node6 [label="6"];
node7 [label="7"];
node1 -> node2;
node1 -> node6;
node2 -> node3;
node2 -> node4;
node3 -> node5;
node4 -> node5;
node6 -> node7;
node7 -> node5;
}
```
when split horizontally could result in `first_graph` being
```
digraph taskgraph {
node1 [label="1"];
node2 [label="2"];
node4 [label="4"];
node5 [label="5"];
node1 -> node2;
node2 -> node4;
node4 -> node5;
}
```
and `second_graph` being
```
digraph taskgraph {
node1 [label="1"];
node3 [label="3"];
node5 [label="5"];
node6 [label="6"];
node7 [label="7"];
node1 -> node6;
node3 -> node5;
node6 -> …
```

Fix bug in Graph::split_horizontal

---

examples/python/pytorch/mt5/mt5_ff.py
python/flexflow/torch/model.py

6c4065d3ebe18f26282b337846a7c09c82c02fb8
- Running HuggingFace mT5 using FlexFlow must use the `torch_to_ff()` code path (and not the `torch_to_file()` + `file_to_ff()` code path that uses an intermediate string representation). This is because mT5 has attribute tensors, which we must fetch from the model itself. Writing those tensor values to a string is unwieldy.
- As a result, I previously did not test the `torch_to_file()` + `file_to_ff()` code path. This commit resolves some extraneous errors on that code path and ends with a useful `RuntimeError()` indicating that attributes are not supported for that code path.
- It also factors out the delimiters used in the string representation as global variables to avoid discrepancies in functions that `split()` on the delimiter.
- It also …

[Torch] String IR fixes; better AttributeNode erroring

---

include/flexflow/dominators.h
include/flexflow/graph.h
include/flexflow/graph_structures.h
include/flexflow/model.h
src/runtime/graph.cc
src/runtime/substitution.cc

(graphs specified via mermaid)
```mermaid
graph TD;
Input1 --> A;
Input1 --> B;
Input2 --> A;
Input2 --> B;
A --> C;
B --> C;
```
How to split the above graph, considering that `Input` nodes can be arbitrarily replicated since they have no cost. We can either 
1. Duplicate `Input1` and `Input2`, allowing a parallel split to be applied but losing the similarity between the inputs of `A` and `B`, which could be used for e.g. operator fusion 
```mermaid
graph TD;
Input1 --> A;
Input2 --> A;
Input1' --> B;
Input2' --> B;
A --> C;
B --> C;
```
Operator fusion example:
```mermaid
graph TD; 
Input1 --> Conv1;
Weight1 --> Conv1;
Input1 --> Conv2;
Weight2 --> Conv2;
```
could be converted to 
```mermaid
graph TD;
Conv["Conv (1 & 2)"];
Input1 --> Conv;
Weight1 --> Concat;
Weight2 --> Concat;
Concat …
```

Implement input node duplication

---

examples/python/pytorch/cifar10_cnn.py
python/flexflow/torch/model.py

This is a (hacky) workaround that enables loading from a `.ff` file without calling `import torch`. It makes the static method `PyTorchModel.file_to_ff()` available in `model.py`'s namespace and hence able to be imported from other files directly.
I tested that I can run
```
./python/flexflow_python examples/python/pytorch/cifar10_cnn.py -ll:py 1 -ll:gpu 1 -ll:fsize 4096 -ll:zsize 12192
```
when `cnn.ff` is available appropriately and when using CFFI instead of pybind (i.e. `export FF_USE_CFFI=1`).

[PyTorch] Enable `file_to_ff()` without `torch`

---

include/flexflow/model.h
include/flexflow/operator_params.h
include/flexflow/ops/concat.h
include/flexflow/ops/conv_2d.h
include/flexflow/ops/element_binary.h
include/flexflow/ops/linear.h
include/flexflow/parallel_tensor.h
include/flexflow/utils/hash_utils.h
include/flexflow/utils/tuple.h
src/ops/concat.cc
src/ops/conv_2d.cc
src/ops/element_binary.cc
src/ops/linear.cc
src/runtime/model.cc
src/runtime/parallel_tensor.cc

This changes the cache key for Concat and ElementBinary operators to avoid hash collision.
Change the key type of `cached_concat_ops` and `cached_element_binary_ops` to `std::pair<ParallelTensorShapes, Params>` where `ParallelTensorShapes` is `std::vector<ParallelTensorShape>` to encode information of multiple inputs. Add some functions for operators with multiple inputs. @lockshaw do you think it is proper?

Refactor cache key for Concat, ElementBinary

---

include/flexflow/model.h
include/flexflow/operator_params.h
include/flexflow/ops/element_unary.h
include/flexflow/ops/pool_2d.h
src/ops/element_unary.cc
src/ops/pool_2d.cc
src/runtime/simulator.cc

- Refactor cache keys for `ElementUnary` and `Pool2D`
- Open question about whether `inplace` belongs in `ElementUnaryParams` and `ElementBinaryParams`. Currently, I've added it to unary because it is already being serialized and deserialized there but left it out of binary.
@lockshaw let me know if this looks good

Refactor cache keys

---

jupyter_notebook/README.md
jupyter_notebook/flexflow_kernel_nocr.py
jupyter_notebook/flexflow_python.json
jupyter_notebook/install.py

I recently implemented the jupyter notebook support (single node) for legion python binding, so I cherry picked the code into FlexFlow, such that we are able to run FlexFlow code in jupyter notebook. If we plan to use `legion_python` instead of our own `flex flow_python` in the future, we can just use the jupyter support from Legion. Feel free to take a look at the instruction in README.md.
Current issues: we have a lot of prints in the C++ code, especially the accuracy, so we will see them printed in red color in jupyter notebook, while the regular python `print` is printed in black.

add jupyter notebook support

---

src/ops/reshape.cc
src/runtime/operator_params.cc

This change (partially) fixes the error reported by Byungsoo:
```
[Meausre Reshape] name(view_1000002_2000002) forward_time(0.0036) backward_time(0.0029) 
terminate called after throwing an instance of 'std::runtime_error'
what():  No overload of get_params_hash defined for op type Transpose
```

Partially resolve transpose no get_params_hash overload issue

---

docs/source/pytorch.rst

This PR wraps the `ffmodel.compile()` line in the PyTorch code example to make it more readable:
https://flexflow.readthedocs.io/en/latest/pytorch.html

[Docs][Easy] Wrap long line for readability

---

.github/workflows/build.yml

The current CI workflows only test the build / installation of FlexFlow using the Cmake system. As a result, changes that break the Makefile system (like my own PR #389 ) go un-noticed. This PR introduces a new job in the `build` workflow, running in parallel to the existing one, testing the build with Makefile.

[Makefile] - Add makefile check to `build` workflow

---

.github/workflows/helpers/install_cudnn.sh

Fix Shellcheck by adding double quotes 
Linked Issues:
- Issue #
- Closes #

Shellcheck fix in `install_cudnn.sh`

---

include/flexflow/ops/kernels/split_kernels.h
include/flexflow/ops/split.h
src/ops/kernels/split_kernels.cpp
src/ops/kernels/split_kernels.cu
src/ops/split.cc

This PR removes kernel functions from `split.h` and `split.cc` into separate `split_kernels.h`, `split_kernels.cu`, and `split_kernels.cpp`.
Linked Issues:
- Issue #303 
- Closes #436 

[Split] Kernel refactor

---

.github/workflows/gpu-ci-daemon.yml
.github/workflows/gpu-ci-skip.yml

This PR prevents Github from running the `gpu-ci-daemon` workflows on forks, where it's not needed and would cause an error.
Linked Issues:
- Issue #
- Closes #

[CI] - disable gpu-ci-daemon workflow on forks

---

src/ops/aggregate.cc
src/ops/aggregate_spec.cc
src/ops/group_by.cc
src/ops/topk.cc

Implement `measure_operator_costs()` for `aggregate`, `aggregate_spec`, `group_by`, `topk`. No implementation for `cost_metrics.backward_time` at the moment since we are designing for inference. **BLOCKED:** @jiazhihao making changes to `aggregate` to only one input.
Linked Issues:
- Issue #
- Closes #

Implement measure operator costs

---

examples/cpp/inference/mixture_of_experts/moe.cc
src/ops/aggregate.cc
src/ops/experts.cc
src/runtime/ffconst_utils.cc

Update the MoE example to use the new experts layer. 
Linked Issues:
- Issue #
- Closes #

[MOE] update moe cpp example and aggregate implementation

---

INSTALL.md

Linked Issues:
- Issue #
- Closes #

[Docs] - Fix error in instructions on how to use Python interface

---

include/flexflow/ops/dropout.h
include/flexflow/ops/kernels/dropout_kernels.h
src/ops/dropout.cc
src/ops/fused.cpp
src/ops/fused.cu
src/ops/kernels/dropout_kernels.cpp
src/ops/kernels/dropout_kernels.cu
src/ops/kernels/element_binary_kernels.cu
src/ops/kernels/flat_kernels.cu

This PR removes kernel functions from `dropout.h` and refactors `dropout.cu` and `dropout.cpp`. 
Linked Issues:
- Issue #303 
- Closes #442 

Dropout kernels

---

src/ops/fused.cc

This is a fix for the aliased/interfering region error. We also need to check duplicate region for the first operator in a FusedOp (e.g., MHA op is the first op fused).
Linked Issues:
- Issue #
- Closes #

Fusion check duplicate region

---

examples/cpp/inference/dataloader.cc
examples/cpp/inference/dataloader.h
examples/cpp/inference/mixture_of_experts/moe.cc
examples/cpp/inference/transformers/transformers.cc
src/ops/experts.cu
src/runtime/inference_manager.cc
src/runtime/parallel_tensor.cc

Fixed an issue with the parallel_tensor equals and applied clang format.
Linked Issues:
- Issue #
- Closes #

[Inference] Fixed parallel_tensor equals

---

examples/cpp/inference/data_generator.cc
examples/cpp/inference/data_generator.cpp
examples/cpp/inference/data_generator.h
examples/cpp/inference/dataloader.cc
examples/cpp/inference/dataloader.cu
examples/cpp/inference/dataloader.h
examples/cpp/inference/inference_config.h
examples/cpp/inference/mixture_of_experts/moe.cc
examples/cpp/inference/transformers/transformers.cc
include/flexflow/batch_config.h
include/flexflow/ffconst.h
include/flexflow/model.h
include/flexflow/operator_params.h
include/flexflow/ops/arg_topk.h
include/flexflow/ops/arg_topk_params.h
include/flexflow/ops/embedding.h
include/flexflow/utils/cuda_helper.h
src/ops/arg_topk.cc
src/ops/arg_topk.cpp
src/ops/arg_topk.cu
src/ops/embedding.cc
src/runtime/batch_config.cc
src/runtime/cuda_helper.cu
src/runtime/ffconst_utils.cc
src/runtime/graph.cc
src/runtime/hip_helper.cpp
src/runtime/model.cc
triton/src/types.h

This PR completes the implementation of the autoregressive inference functionalities, by obtaining the new token generated at each iteration of the inference process, and saving it into memory, as well as passing it to the next iteration's batch.
In addition, we update the transformer & MoE models to take integers as inputs, and apply the embedding.
Linked Issues:
- Issue #
- Closes #

[Inference] - Pass generated tokens to next batch

---

include/flexflow/operator.h
src/ops/aggregate.cc
src/ops/aggregate_spec.cc
src/ops/arg_topk.cc
src/ops/attention.cc
src/ops/element_binary.cc
src/ops/embedding.cc
src/ops/experts.cc
src/ops/group_by.cc
src/ops/inc_multihead_self_attention.cc
src/ops/inc_multihead_self_attention.cu
src/ops/layer_norm.cc
src/ops/linear.cc
src/ops/noop.cc
src/ops/softmax.cc
src/ops/topk.cc
src/runtime/inference_manager.cc
src/runtime/model.cc

This PR fixes an issue where multiple branches may share the same OpMeta. After the fix, each branch now has it's own OpMeta for each operator.
Linked Issues:
- Issue #
- Closes #

[Inference init] create multiple OpMeta, one for each batch

---

include/flexflow/ops/inc_multihead_self_attention.h
src/ops/inc_multihead_self_attention.cu

reload the weights because the origin weights is set before set_tensor
fix the index in weight_O
Linked Issues:
- Issue #
- Closes #

reload the weight if set_tensor, fix the index

---

.github/workflows/multinode-test.yml
CMakeLists.txt

We increase the timeout in the two multinode-test jobs that are unable to complete within the default job timeout of 6h (360mins). See the last test failure: https://github.com/flexflow/FlexFlow/actions/runs/5280569469
Linked Issues:
- Issue #
- Closes #

[CI] - Increase timeout in multinode test (UCX & MPI)

---

INSTALL.md

Fix issue where `INSTALL.md` instructions run the python example from the wrong directory. 
Linked Issues:
- Issue #
- Closes #

Fix directory in python example in INSTALL.md

---

README.md

Specify that second code block is Python to have correct code color in README.md
Linked Issues:
- Issue #818 
- Closes #818

Fix Code Color in README

---

README.md

Update link to c++ examples in README.md
Linked Issues:
- Issue #
- Closes #

Update README.md C++ Examples List

---

lib/utils/include/utils/graph/README.md

Add symbols and area labels to mermaid charts of MultiDiGraph
Linked Issues:
- Issue #826
- Closes #826

Label Chart Elements

---

docker/flexflow-environment/Dockerfile

a quick temporary fix to use 11.7.1 in master since 11.7.0 is actually deleted. 
Linked Issues:
- Issue #
- Closes #

fix 11.7.0 to 11.7.1

---

cmake/cuda.cmake
lib/utils/CMakeLists.txt

On machines where the cuda headers were not automatically being searched, a build error would result in `utils/fp16.h`. This fixes that by explicitly adding the found cuda include directories to the requirements of `utils`.
Linked Issues:
- Issue #
- Closes #825

Fix `cuda_fp16.h` not found issue

---

.github/workflows/docker-build.yml
docker/build.sh
docker/flexflow-environment/Dockerfile
docker/flexflow/Dockerfile
docker/publish.sh

Add optional flag for cuda version and build docker images based on the corresponding cuda version input. This PR takes `cuda_version=11.8` as input. 
Linked Issues:
- Issue #
- Closes #

add optional flag ann test with 11.8 cuda version

---

lib/utils/include/utils/containers.h
lib/utils/include/utils/stack_map.h
lib/utils/include/utils/stack_vector.h
lib/utils/include/utils/type_traits.h

Generalize Containers.h to use iterator types
Linked Issues:
- Issue #
- Closes #

Generalize Containers.h

---

docker/run.sh

Fix the `docker inspect` error message printing issue.
Modify the original way to check the existence of the docker image so that run a command `the docker images -q ... ` and check if it exists or not (you can check if the exit code is 0 or something else) and in case it doesn't exist, print our error message, otherwise, just continue without doing anything.
Linked Issues:
- Issue #
- Closes #

Docker Inspect Error Msg Prinitng Fix

---

lib/utils/include/utils/containers.h
lib/utils/include/utils/type_traits.h
lib/utils/include/utils/type_traits_core.h

Linked Issues:
- Issue #
- Closes #

fix compile errors from filter and support_interator_tag

---

.github/workflows/gpu-ci.yml
.github/workflows/multinode-test.yml

Linked Issues:
- Issue #
- Closes #

Fix container name in GPU CI tests

---

src/runtime/request_manager.cc

This PR enables Legion's tracing optimization for FlexFlow Serve.
Linked Issues:
- Issue #
- Closes #

Enable legion tracing for incr_decoding and spec_infer

---

include/flexflow/batch_config.h
inference/models/configs/llama_68M.json
inference/utils/convert_llama_config.py
src/runtime/request_manager.cc

In the edge case of exactly `MAX_NUM_TOKENS` in the first verify batch, the extra token generated by the large model will overflow and mess up the depth.
Also added the config file of llama_68M to inference/model/configs and a tool to convert the hugging face LLaMA config to SpecInfer LLaMA config.
Linked Issues:
- Issue #900 
- Closes #900 

[Bug] Fix edge case when we have exactly MAX_NUM_TOKENS in the first verify batch

---

.github/workflows/pip-deploy.yml

1. Deploy to pip automatically for each tag
3. Tags can then be created manually (or automatically during a release)
4. Right now, only deploy to test pip for testing
Linked Issues:
- Issue #
- Closes #

Deploy to `pip`

---

CMakeLists.txt

This PR fixes a lib link error we encountered on the Catalyst cluster
Linked Issues:
- Issue #
- Closes #

Fix a potential link error

---

src/ops/attention.cc
src/ops/batch_norm.cc
src/ops/concat.cc
src/ops/dropout.cc
src/ops/element_binary.cc
src/ops/element_unary.cc
src/ops/flat.cc
src/ops/layer_norm.cc
src/ops/linear.cc
src/ops/reduce.cc
src/ops/reverse.cc

The variables captured by std::function go out of scope, resulting in runtime errors. Instead, copy the values so they persist after the lexical block. 
Linked Issues:
- Issue #
- Closes #906 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/flexflow/FlexFlow/958)

Fixes #906. Capture variables in lambda by copy.

---

lib/runtime/src/legion_backing.cc
lib/runtime/src/ops/aggregate_spec.cc
lib/runtime/src/ops/attention.cc
lib/runtime/src/task_spec/device_specific.h
lib/runtime/src/task_spec/op_arg_ref.h
lib/runtime/src/task_spec/op_task_invocation.h
lib/runtime/src/task_spec/runtime_arg_ref.cc
lib/runtime/src/task_spec/runtime_arg_ref.h
lib/runtime/src/task_spec/task_argument_accessor.h

Rename DeviceSpecificArg to DeviceSpecific
Linked Issues:
- Issue #904
- Closes #904
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/flexflow/FlexFlow/1009)

Rename DeviceSpecificArg to DeviceSpecific

---

include/flexflow/request_manager.h
python/flexflow/serve/serve.py
src/runtime/request_manager.cc

This PR enables early stop, which will allow `llm.generate` to return immediately when an EOS token is generated.
Linked Issues:
- Issue #
- Closes #1013

Allow FlexFlow Serve to stop when EOS token is generated

---

include/flexflow/utils/hash_utils.h

Copied Boost's implementation.
Linked Issues:
- Issue #902 
- Closes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/flexflow/FlexFlow/1021)

Use Boost's hash_combine for 32 and 64-bit values (#902)

---

docker/flexflow-environment/Dockerfile
inference/python/spec_infer.py
src/ops/spec_inc_multihead_self_attention.cu
src/runtime/request_manager.cc
tests/inference/cpp_inference_tests.sh
tests/inference/huggingface_inference.py
tests/inference/python_inference_tests.sh
tests/inference/python_test_configs/generate_configs.py
tests/inference_tests.sh

- Fix CI issues affecting the Inference Test workflow
- Fix bug in Falcon model text generation
- Add alignment with Huggingface for Falcon/OPT models to CI
Linked Issues:
- Issue #
- Closes #

Fix Falcon model, inference test in CI

---

python/flexflow/serve/__init__.py

Linked Issues:
- Issue #
- Closes #

Set number of CPUS to 4 by default in inference mode

---

.github/workflows/per-lib-check.yml

The `per-lib-check` workflow from the repo refactor branches uses 16 runners at a time (for each commit / PR), out of the 20 in total that we have available for the repo. This PR serializes the jobs so that workflows from other branches / users / PRs do not starve
Linked Issues:
- Issue #
- Closes #

Serialize jobs in `per-lib-checks` workflow

---

include/flexflow/batch_config.h
src/runtime/request_manager.cc

Minimize token loading overhead for small requests in batches. Reduce the decoding step of the loading prompt to 1 step.
Linked Issues:
- Issue #
- Closes #

[SpecInfer] Reduce single request per batch overhead

---

python/flexflow_python_build.py

`-ef` is "True if file1 and file2 refer to the same device and inode numbers."
Linked Issues:
- Issue #
- Closes #957
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/flexflow/FlexFlow/1173)

Compare file paths reliably

---

include/flexflow/batch_config.h
src/ops/inc_multihead_self_attention.cu
src/ops/spec_inc_multihead_self_attention.cu
src/ops/tree_inc_multihead_self_attention.cu
src/runtime/batch_config.cc
src/runtime/beam_search_batch_config.cc
src/runtime/request_manager.cc
src/runtime/tree_verify_batch_config.cc

Add `first_token_offset_in_batch` in `PerRequestInfo` to indicate the offset of the request's first token in a `BatchConfig`
Linked Issues:
- Issue #
- Closes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/flexflow/FlexFlow/1197)

Add `first_token_offset_in_batch` to indicate the offset of the request's first token in a `BatchConfig`

---

src/ops/inc_multihead_self_attention.cu
src/ops/spec_inc_multihead_self_attention.cu
src/ops/tree_inc_multihead_self_attention.cu

This PR updates the layout of `m->attn_heads` from `[num_heads, vProjSize, num_tokens]` to `[num_tokens, num_heads, vProjSize]`. This change makes its layout consistent with other tensors in multihead attention.
This PR also fixes a offset calculation bug in `spec_inc_mha`. We used to assume that requests are ranked in the exact same order as the tokens, which is no longer true after several RequestManager changes. As a result, we may get the following requestsInfo. Note that request 4 uses token 135 - 150. The fix is to remove this assumption and use `first_token_offset_in_batch` to calculate token offsets.
```
(gdb) p bc->requestsInfo
$3 = {{first_token_depth_in_request = 96, first_token_offset_in_batch = 0, num_tokens_in_batch = 9, max_sequence_length = 128, …
```

Update the data layout of m->attn_heads

---

.github/README.md
CMakeLists.txt
SERVE.md
config/config.inc
include/flexflow/ffconst.h
inference/incr_decoding/incr_decoding.cc
inference/python/spec_infer.py
inference/spec_infer/spec_infer.cc
python/flexflow/type.py
src/runtime/request_manager.cc
tests/inference/cpp_inference_tests.sh
tests/inference/python_inference_tests.sh
tests/inference/python_test_configs/generate_configs.py
tests/inference_tests.sh

PR #1219 changed the prompt used in the CI tests, resulting in the generated text starting at the very first line of the output. The bash files checking the alignment between FlexFlow and Huggingface, however, still assume that the generated text starts at the second line of the output, so the first line of output is not checked. This PR fixes this bug.
In addition, this PR fixes several latent issues (which we had postponed for a long time) related to the llama tokenizer. And we go back to using the original `JackFram/llama-160m` (instead of `JackFram/llama-160m-base`) after aligning the configs with the official LLAMA model ([see here](https://huggingface.co/JackFram/llama-160m/discussions/12))
Linked Issues:
- Issue #
Issues closed by …

Fix inference tests in CI

---

src/ops/inc_multihead_self_attention.cpp
src/ops/inc_multihead_self_attention.cu
src/ops/kernels/linear_kernels.cpp
src/ops/kernels/linear_kernels.cu
src/ops/spec_inc_multihead_self_attention.cpp
src/ops/spec_inc_multihead_self_attention.cu
src/ops/tree_inc_multihead_self_attention.cpp
src/ops/tree_inc_multihead_self_attention.cu

This PR updates the default compute type used by the cuBLAS lib. When CUDA_VERSION is missing, we use CUBLAS_COMPUTE_16F for better performance.
Linked Issues:
- Issue #
- Closes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/flexflow/FlexFlow/1209)

Update the default cublas behavior when CUDA_VERSION is not specified

---

include/flexflow/batch_config.h
include/flexflow/ops/inc_multihead_self_attention.h
include/flexflow/ops/kernels/inc_multihead_self_attention_kernels.h
include/flexflow/ops/kernels/inc_multihead_self_attention_utils.cuh
include/flexflow/ops/spec_inc_multihead_self_attention.h
src/ops/inc_multihead_self_attention.cu
src/ops/spec_inc_multihead_self_attention.cu
src/ops/tree_inc_multihead_self_attention.cu
src/runtime/request_manager.cc

Linked Issues:
- Issue #
- Closes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/flexflow/FlexFlow/1228)

Optimize attention kernel

---

lib/kernels/include/kernels/embedding_kernels.h
lib/kernels/src/cuda/embedding_kernels.cu
lib/kernels/src/hip/embedding_kernels.cpp
lib/runtime/src/ops/embedding.cc
lib/runtime/src/ops/embedding.h

Linked Issues:
- Issue #
- Closes #1057
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/flexflow/FlexFlow/1256)

Embedding Operator

---

include/flexflow/model.h
inference/models/opt.cc
python/flexflow/serve/models/opt.py
src/ops/kernels/linear_kernels.cu
src/runtime/model.cc

Linked Issues:
- Issue #
- Closes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/flexflow/FlexFlow/1265)

Fuse bias and relu in OPT

---

CMakeLists.txt
cmake/expected.cmake
flake.lock
flake.nix

Add option to use external tl::expected
Add `proj` directly as a flake instead of through a submodule
Linked Issues:
- Issue #
- Closes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/flexflow/FlexFlow/1347)

Add option to use external tl::expected

---

python/flexflow/serve/serve.py

fix `python/serve/serve.py` typo: 
```bash
File "/usr/FlexFlow/python/flexflow/serve/serve.py", line 378, in compile
in self.model_configs.__dict__
^^^^^^^^^^^^^^^^^^
AttributeError: 'LLM' object has no attribute 'model_configs'
```
Linked Issues:
- Issue #
- Closes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/flexflow/FlexFlow/1358)

fix: 'model_configs' AttributeError

---

CMakeLists.txt
cmake/Modules/CodeCoverage.cmake
flake.nix

Hi @lockshaw, this is the PR for code coverage
I added code coverage support in cmake lists
My next step would be about integrating the output codecoverage into reviewable
Linked Issues:
- Issue #1340 
- Closes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/flexflow/FlexFlow/1380)

Code Coverage Support

---

include/flexflow/flexflow_c.h
include/flexflow/ops/kernels/lora_linear_kernels.h
include/flexflow/ops/lora_linear_params.h
inference/peft/peft.cc
inference/python/ff_peft.py
inference/utils/download_peft_model.py
python/flexflow/core/flexflow_cffi.py
python/flexflow/serve/models/llama.py
python/flexflow/serve/serve.py
python/flexflow/type.py
src/c/flexflow_c.cc
src/ops/kernels/lora_linear_kernels.cu
src/ops/lora_linear.cc
src/ops/lora_linear_params.cc
src/runtime/batch_config.cc
tests/peft_test.sh

Linked Issues:
- Issue #
- Closes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/flexflow/FlexFlow/1441)

Optimizers python interface

---

python/flexflow/flexflow_python

Fixes LD_LIBRARY_PATH typo in pip's version of flexflow_python
Linked Issues:
- Issue #
- Closes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/flexflow/FlexFlow/1461)

pip flexflow_python typo

---

include/flexflow/request_manager.h
inference/incr_decoding/incr_decoding.cc
src/runtime/request_manager.cc

Support two simple SLO-aware scheduling policy based on continuous batching: FCFS and Smallest Time to Attain (STTA).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/flexflow/FlexFlow/1554)

Coutinuous batching schedulers

---

README.md

Update README post-repo-split. This new README is a temporary placeholder whose main purpose is to avoid any flexflow-train/flexflow-serve confusion, and will get expanded over time.
Linked Issues:
- Issue #
- Closes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/flexflow/flexflow-train/1560)

Update README to reference flexflow-serve

---

lib/utils/include/utils/containers/recurse_n.h
lib/utils/src/utils/containers/recurse_n.cc
lib/utils/test/src/utils/containers/recurse_n.cc

added recurse_n function in containers library
Linked Issues:
- Issue #
- Closes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/flexflow/flexflow-train/1563)

added recurse_n

---

flake.lock

#1578 updated to a new version of proj that contained a bug in the `proj build` command, this commit updates nix-locked proj to version https://github.com/lockshaw/proj/commit/e2400466cf6ffa3e2c231449add3c47d0298d045 which contains a fix.
Linked Issues:
- Issue #
- Closes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/flexflow/flexflow-train/1580)

Fix proj build command

---

flake.lock

dtgen now supports specifying Doxygen docstrings in `.struct.toml` ([top-level docstring example](https://github.com/lockshaw/proj/blob/2394e855baeea5757c75eadde748902988db5509/tests/dtgen/person/include/person.struct.toml#L3-L7), [field docstring example](https://github.com/lockshaw/proj/blob/2394e855baeea5757c75eadde748902988db5509/tests/dtgen/person/include/person.struct.toml#L33)), `.enum.toml` ([top-level docstring example](https://github.com/lockshaw/proj/blob/2394e855baeea5757c75eadde748902988db5509/tests/dtgen/person/include/color.enum.toml#L3-L7), [value docstring example](https://github.com/lockshaw/proj/blob/2394e855baeea5757c75eadde748902988db5509/tests/dtgen/person/include/color.enum.toml#L23)), and `.variant.toml` ([top-level docstring …

Update dtgen to add docstring support

---

.github/workflows/tests.yml
flake.nix

Automatically push build dependencies to `ff.cachix.org` in CI (for `master` only).
Linked Issues:
- Issue #
- Closes #
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/flexflow/flexflow-train/1603)

Automatically push deps to cachix in CI
